name: odooku
version: '10.0.6'
summary: Easily run Odoo as a service through Odooku.
description: |
  Easily run Odoo as a service through Odooku. Odooku follows the
  principes defined by the 'Twelve-Factor App'.

grade: devel
confinement: strict

apps:
  odooku:
    command: odooku
  odooku-posbox:
    command: odooku wsgi 8069 --server-wide-modules=web,hw_proxy,hw_escpos 
    daemon: simple
    stop-timeout: 10s
    plugs:
      - network-bind
      - network-control
      - raw-usb

parts:
  odooku-python:
    build-packages:
      - git
      - libpq-dev
      - libxml2-dev
      - libxslt1-dev
      - libldap2-dev
      - libsasl2-dev
      - libssl-dev
      - libtiff5-dev
      - libjpeg8-dev
      - zlib1g-dev
      - libfreetype6-dev
      - libwebp-dev
    stage-packages:
      - libusb-1.0-0
    plugin: python
    python-version: python2
    requirements: requirements.txt
