name: odooku
version: '10.0.0'
summary: Easily run Odoo as a service through Odooku.
description: |
  Easily run Odoo as a service through Odooku. Odooku follows the
  principes defined by the 'Twelve-Factor App'.

grade: devel
confinement: strict

apps:
  odooku:
    command: odooku

parts:
  odooku-python:
    build-packages:
      - git
      - libpq-dev
      - libxml2-dev
      - libxslt1-dev
      - libldap2-dev
      - libsasl2-dev
      - libssl-dev
    plugin: python
    python-version: python2
    requirements: requirements.txt
