name: odooku
version: '10.0.2'
summary: Easily run Odoo as a service through Odooku.
description: |
  Easily run Odoo as a service through Odooku. Odooku follows the
  principes defined by the 'Twelve-Factor App'.

grade: devel
confinement: strict

apps:
  odooku:
    command: odooku
    plugs:
      - network-bind
      - raw-usb

parts:
  odooku-python:
    build-packages:
      - git
      - libpq-dev
      - libxml2-dev
      - libxslt1-dev
      - libldap2-dev
      - libsasl2-dev
      - libssl-dev
      - libtiff5-dev
      - libjpeg8-dev
      - zlib1g-dev
      - libfreetype6-dev
      - libwebp-dev
      - libusb-1.0-0-dev
    plugin: python
    python-version: python2
    requirements: requirements.txt
